import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {/* <Script
          src="https://bsideai.vercel.app/snippet.js"
          data-bside-project="0b5c73cf-609f-4f37-8e72-407640d0520d"
          data-bside-base="https://bsideai.vercel.app/"
          strategy="beforeInteractive"
        /> */}
        {children}
      </body>
    </html>
  );
}
